# Site settings
title: Portfolio
email: luke4.roberts@live.uwe.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  My portfolio and Development Blog.
baseurl: /
url: https://LAMRoberts.github.io  # the base hostname & protocol for your site
twitter_username: LAMRoberts
github_username:  LAMRoberts

# SASS directory
sass:
   sass_dir: ./_sass/
    
# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Build settings
markdown: kramdown
hightlighter: 'rouge' 

# Pagination
paginate: 2
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

